CREATE TABLE [tblUsers] (
    UserID INT NOT NULL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    UserName VARCHAR(50) NOT NULL,
    Password VARCHAR(28) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    IconPic VARCHAR(255) NOT NULL,
    Bio TEXT NOT NULL,
    DateOfBirth DATETIME NOT NULL
    );