CREATE TABLE [tblUsers] (
    UserID INT NOT NULL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    UserName VARCHAR(50) NOT NULL,
    Password VARCHAR(28) NOT NULL,
    DateOfBirth DATETIME NOT NULL
    );